name: 'DartFileServer'
version: 0.0.1
description: A basic file server in Dart
#author: Rudy Reeves

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  http_server: "^0.9.5+1"
  path: "^1.3.8"
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
- dart_to_js_script_rewriter